# Generated by Django 4.2.9 on 2024-02-06 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_collection_featured_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
